# Generated by Django 3.2.11 on 2022-04-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acuityapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assess',
            old_name='fromUser',
            new_name='from_user',
        ),
        migrations.RemoveField(
            model_name='assess',
            name='toUser',
        ),
        migrations.AddField(
            model_name='assess',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='acuityapp.user'),
            preserve_default=False,
        ),
    ]
