# Generated by Django 3.2.11 on 2022-03-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acuityapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
