# Generated by Django 3.2.11 on 2022-03-15 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acuityapp', '0002_assess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assess',
            name='judge',
        ),
        migrations.AddField(
            model_name='assess',
            name='fromUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assess',
            name='toUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to='auth.user'),
            preserve_default=False,
        ),
    ]
