# Generated by Django 3.2.11 on 2022-03-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuityapp', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='assess',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
