# Generated by Django 3.2.11 on 2022-03-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuityapp', '0003_assess_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score_mean',
            field=models.IntegerField(default=3),
        ),
    ]
